version: "3"

services:
  mysql:
    image: mysql:5.7
    container_name: fake_buscape
    ports:
      - "3306:3306"
    volumes:
      - /var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: fake-buscape
      MYSQL_USER: root
      MYSQL_PASSWORD: root
