version: "3"

services: 
  mysql:
    image: mysql:5.7
    command: mysqld --sql_mode=""
    ports:
      - "3306:3306"
    restart: always    
    volumes: 
      - /var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_USER: root
      MYSQL_PASSWORD: root123      