version: '3'

services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    command: mysqld --sql_mode=""
    ports:
      - '3306:3306'
    restart: always
    volumes:
      - /var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_PASSWORD: password123
      MYSQL_DATABASE: mysql_shop
