version: "3"

services:
  mysql:
    image: mysql:5.7
    container_name: uber_db
    command: mysqld --sql_mode=""
    ports:
      - "3306:3306"
    restart: always
    volumes: 
      - /opt/databases/mysql:/var/lib/mysql:rw
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hackaton
      MYSQL_USER: root
      MYSQL_PASSWORD: password123