version: "3"

services:
  express-final:
    image: mysql:5.7
    container_name: db_mysql
    ports:
      - "3306:3306"
    volumes:
      - /opt/databases/mysql:/var/lib/mysql:rw
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: auth
      MYSQL_USER: root
      MYSQL_PASSWORD: password123
